//#region App String
export { HOME_HEADING, HOME_PARA, LOGO_TEXT, PHONE_HEADING, EMAIL_HEADING, BOTTOM_NOTE, OTP_HEADING, NOT_RECEIVED, FULL_NAME_HEADING, FULL_NAME_NOTE, AVATAR_HEADING, AVATAR_SUBHEADING, AVATAR_CHOOSE } from './AppString'
//#endregion

//#region App Image
export { LOGO, PIC_AVATAR_DEF, IC_BACK_ARROW,IC_ARROW_FORWARD,IC_ARROW_LEFT,IC_MUTED,IC_UNMUTED,IMG_QUITE,IMG_HANDS_UP, IC_LOGOUT, IC_SEARCH, IC_CLOSE, IC_START_ROOM, IMG_PHONE, IMG_EMAIL, IMG_GO, IC_PHONE, IC_EMAIL, IMG_LOCK, IC_USER, IMG_FULLNAME, IMG_DONE, PIC_CHAT_BUBBLE, PIC_FEMALE_1, PIC_FEMALE_2, PIC_FEMALE_3, PIC_FEMALE_4, PIC_FEMALE_5, PIC_MALE_1, PIC_MALE_2, PIC_MALE_3, PIC_MALE_4, PIC_OPEN, PIC_SOCIAL, PIC_PRIVATE } from './AppImage'
//#endregion